// Generated by CoffeeScript 1.10.0
(function() {
  jQuery(function() {
    $(".sliding-link").on("click", function() {
      event.preventDefault();
      $('html,body').animate({
        scrollTop: $(this.hash).offset().top
      }, 400);
    });
  });

}).call(this);
