// Generated by CoffeeScript 1.10.0
(function() {
  var checkOverflow300, checkOverflow400;

  jQuery(function() {
    $(".sliding-link").click(function() {
      event.preventDefault();
      return $('html,body').animate({
        scrollTop: $(this.hash).offset().top
      }, 400);
    });
    $(".toggle-more").click(function() {
      if ($(this).parent().hasClass('expanded')) {
        return $(this).parent().removeClass('expanded');
      } else {
        return $(this).parent().addClass('expanded');
      }
    });
    $(".slide-toggle").click(function() {
      $('#hamburger').toggleClass('open');
      $('.nav-slider').toggleClass('open');
      $('.dimmer').toggleClass('open');
      return $('body').toggleClass("fixed-position");
    });
    return $('#nav-portfolio').click(function() {
      $('.portfolio-menu').toggleClass('open');
      $('.primary-menu').toggleClass('portfolio-opened');
    });
  });

  $(window).load(function() {
    checkOverflow300();
    return checkOverflow400();
  });

  $(window).resize(function() {
    checkOverflow300();
    return checkOverflow400();
  });

  checkOverflow400 = function() {
    return $('.overflowable400').each(function() {
      return $(this).toggleClass('overflowed400');
    });
  };

  checkOverflow300 = function() {
    return $('.overflowable300').each(function() {
      return $(this).toggleClass('overflowed300');
    });
  };

}).call(this);
